# **Linear Program**

In [2]:
!pip install cvxpy

In [3]:
import cvxpy as cp
import numpy as np

In [4]:
x=cp.Variable(2)

In [5]:
x=cp.Variable(5)
cp.norm(x,1)

Expression(CONVEX, NONNEGATIVE, ())

In [6]:
cp.exp(x)

Expression(CONVEX, NONNEGATIVE, (5,))

In [7]:
cp.log(x)

Expression(CONCAVE, UNKNOWN, (5,))

In [8]:
cp.norm(x,1)+cp.exp(x)

Expression(CONVEX, NONNEGATIVE, (5,))

In [9]:
x=cp.Variable()
y=cp.Variable()
cp.kl_div(x,y)

Expression(CONVEX, NONNEGATIVE, ())

In [15]:
cp.power(x,4)

Expression(CONVEX, NONNEGATIVE, ())

In [ ]:
cp.power(x,1)+cp.power(y,1)

Expression(AFFINE, UNKNOWN, ())

In [ ]:
cp.power(x,1)+cp.power(y,1)+cp.norm(x,1)

Expression(CONVEX, UNKNOWN, ())

In [16]:
#Problem of class

In [17]:
x=cp.Variable(2)

In [ ]:
A = np.array([[-2,-1], [-1,-2]])
A

array([[-2, -1],
       [-1, -2]])

In [ ]:
b=np.array([-8,-10]).T
b

array([ -8, -10])

In [ ]:
c=np.array([50,70]).T
c

array([50, 70])

In [ ]:
x = cp.Variable(2)
prob = cp.Problem(cp.Minimize(c.T@x),
                 [A @ x <= b])
prob.solve()
# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)


The optimal value is 379.9999999903208
A solution x is
[2. 4.]
